### ISSUE TITLE
Mi5 7.0 props don't work

### ISSUE THREAD

**Issue by Acid-miuipolskapl** [DeicPro/xiaomi-safetynet-fix#3]
The old props work:
`6.0.1 MXB48T V8.1.2.0.MAAMIDI`
new one don't. CTS mismatch.

Actually you can use 6.0 stable props without problems on latest dev/xiaomi.eu roms based on 7.0.

**Comment by DeicPro** [comment]
fixed, thanks you

**Comment by auanasgheps** [comment]
Hi,
Can you please show where have you made the change?
post-fs-data.sh is still showing 
gemini) set_prop "6.0.1" "MXB48T" "V8.1.2.0.MAAMIDI"

**Comment by DeicPro** [comment]
What is the problem @auanasgheps? The code you quoted is correct.

**Comment by auanasgheps** [comment]
@DeicPro Sorry, later I realised that I didn't understand the fix, so I deleted the comment. However, these props still don't work (apparently). Just posted logs on XDA discussion, but can post them here too if you like.

**Comment by DeicPro** [comment]
@auanasgheps the prop works, what doesn't work is Magisk Hide in your device.
