### ISSUE TITLE
Xiaomi Redmi Pro ( omega ) 

### ISSUE THREAD

**Issue by ghost** [DeicPro/xiaomi-safetynet-fix#4]
Xiaomi Redmi Pro not working please update 
![screenshot_2017-05-28-22-49-06-877_com topjohnwu magisk](https://cloud.githubusercontent.com/assets/12477281/26533254/c4b71b84-4416-11e7-8ec1-9899e89987f0.png)
![screenshot_2017-05-28-22-48-59-063_com topjohnwu magisk](https://cloud.githubusercontent.com/assets/12477281/26533255/c793fe30-4416-11e7-91ef-b559ae4ffb4e.png)

**Comment by DeicPro** [comment]
Is not working because is not supported too...

Equally Magisk Hide does not work on your device, so adding support to omega does not mean you will bypass SafetyNet, you must try to disable Busybox, systemless host and all modules to try if is related with them.

**Comment by DeicPro** [comment]
Fixed https://github.com/DeicPro/xiaomi-safetynet-fix/commit/96cb3436064638dbb7fe5629269246aca0616a3a
