### ISSUE TITLE
Revert latest SafetyNet hotfix

### ISSUE THREAD

**Issue by coderobe** [DeicPro/xiaomi-safetynet-fix#6]
Magisk 13.3 obsoletes https://github.com/DeicPro/xiaomi-safetynet-fix/commit/8be81a306ec667cc7c94ccae0c52f5112a74f727

**Comment by DeicPro** [comment]
is needed too due `init.svc.magisk_pfs`, `init.svc.magisk_pfsd` and `init.svc.magisk_service` are not removed. IDK if is because not working Magisk Hide, my device itself or something more.

**Comment by coderobe** [comment]
They are cleared with Magisk 13.3.

**Comment by DeicPro** [comment]
Sadly not.. a lot of users with 13.3 need this too (really I think all)
